//! Immutable Neo N3 chain identity and protocol specification.
//!
//! A node selects one validated `Arc<NeoChainSpec>` at startup. The spec is the
//! single owner of network identity, genesis inputs, protocol limits, and the
//! ordered hardfork schedule. Operator services may read it but cannot mutate a
//! built-in chain into an incoherent hybrid at runtime.

use std::sync::Arc;

use neo_primitives::UInt256;
use thiserror::Error;

use super::public_key::parse_public_key;
use crate::{
    ActiveHardforks, GenesisConfig, GenesisConfigError, Hardfork, HardforkSchedule,
    HardforkScheduleError, NetworkType, ProtocolConfigError, ProtocolSettings,
};

const MAINNET_GENESIS_HASH: &str =
    "0x1f4d1defa46faa5e7b9b8d3f79a06bec777d7c26c4aa5f6f5899a291daa87c15";
const TESTNET_GENESIS_HASH: &str =
    "0x9d3276785e7306daf59a3f3b9e31912c095598bbfb8a4476b821b0e59be4c57a";

/// Stable identity fields used to bind storage, checkpoints, and peer sessions.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChainIdentity {
    name: Arc<str>,
    network_type: NetworkType,
    network_magic: u32,
    expected_genesis_hash: Option<UInt256>,
}

impl ChainIdentity {
    /// Human-readable chain name.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Built-in network family or private-chain marker.
    #[must_use]
    pub const fn network_type(&self) -> NetworkType {
        self.network_type
    }

    /// Neo network magic, which is also the P2P chain discriminator.
    #[must_use]
    pub const fn network_magic(&self) -> u32 {
        self.network_magic
    }

    /// Pinned genesis hash when the chain publishes one.
    #[must_use]
    pub const fn expected_genesis_hash(&self) -> Option<UInt256> {
        self.expected_genesis_hash
    }
}

/// Invalid or internally inconsistent chain specification.
#[derive(Debug, Error)]
pub enum ChainSpecError {
    /// A runnable spec must have a non-empty name.
    #[error("chain name must not be empty")]
    EmptyName,

    /// Embedded or loaded protocol settings could not be constructed.
    #[error("invalid protocol settings: {0}")]
    InvalidProtocol(#[source] ProtocolConfigError),

    /// Genesis configuration failed validation.
    #[error("invalid genesis configuration: {0}")]
    InvalidGenesis(#[source] GenesisConfigError),

    /// Validator count is zero or exceeds the standby committee.
    #[error("validator count {validators_count} is invalid for committee size {committee_len}")]
    InvalidValidatorCount {
        /// Configured consensus validator count.
        validators_count: i32,
        /// Number of standby committee members.
        committee_len: usize,
    },

    /// Genesis and protocol settings describe different validator counts.
    #[error(
        "genesis has {genesis_validators} validators, protocol settings require {protocol_validators}"
    )]
    GenesisValidatorMismatch {
        /// Validator records in genesis.
        genesis_validators: usize,
        /// Validator count in protocol settings.
        protocol_validators: usize,
    },

    /// Genesis and protocol settings contain different committee sizes.
    #[error(
        "genesis committee size {genesis_committee} differs from protocol committee size {protocol_committee}"
    )]
    GenesisCommitteeSizeMismatch {
        /// Committee entries in genesis.
        genesis_committee: usize,
        /// Parsed committee entries in protocol settings.
        protocol_committee: usize,
    },

    /// A genesis committee key is malformed.
    #[error("invalid genesis committee key at index {index}: {reason}")]
    InvalidCommitteeKey {
        /// Committee position.
        index: usize,
        /// Parse failure.
        reason: String,
    },

    /// Genesis and protocol settings contain different committee keys.
    #[error("genesis committee key at index {index} differs from protocol settings")]
    GenesisCommitteeMismatch {
        /// First mismatching committee position.
        index: usize,
    },

    /// The hardfork schedule violates Neo's ordered activation contract.
    #[error("invalid hardfork schedule: {0}")]
    InvalidHardforkSchedule(#[source] HardforkScheduleError),

    /// The pinned genesis hash is malformed.
    #[error("invalid expected genesis hash: {0}")]
    InvalidGenesisHash(String),

    /// The generated genesis block does not match the chain identity pin.
    #[error("genesis hash mismatch: expected {expected}, got {actual}")]
    GenesisHashMismatch {
        /// Pinned chain-spec hash.
        expected: UInt256,
        /// Hash generated by the canonical block builder.
        actual: UInt256,
    },

    /// Private chains require an explicit complete specification.
    #[error("private networks require an explicit NeoChainSpec")]
    PrivateSpecRequired,
}

/// Immutable chain-level configuration shared by every node subsystem.
#[derive(Debug, Clone, PartialEq)]
pub struct NeoChainSpec {
    identity: ChainIdentity,
    protocol_settings: Arc<ProtocolSettings>,
    genesis: Arc<GenesisConfig>,
}

impl NeoChainSpec {
    /// Builds and validates a complete private-chain specification.
    ///
    /// MainNet and TestNet are closed protocol identities and can only be
    /// selected through [`Self::mainnet`] and [`Self::testnet`].
    pub fn private(
        name: impl Into<Arc<str>>,
        protocol_settings: ProtocolSettings,
        genesis: GenesisConfig,
        expected_genesis_hash: Option<UInt256>,
    ) -> Result<Self, ChainSpecError> {
        Self::build(
            name,
            NetworkType::Private,
            protocol_settings,
            genesis,
            expected_genesis_hash,
        )
    }

    fn build(
        name: impl Into<Arc<str>>,
        network_type: NetworkType,
        protocol_settings: ProtocolSettings,
        genesis: GenesisConfig,
        expected_genesis_hash: Option<UInt256>,
    ) -> Result<Self, ChainSpecError> {
        let name = name.into();
        if name.trim().is_empty() {
            return Err(ChainSpecError::EmptyName);
        }

        protocol_settings
            .hardforks
            .validate()
            .map_err(ChainSpecError::InvalidHardforkSchedule)?;
        genesis.validate().map_err(ChainSpecError::InvalidGenesis)?;

        let validators_count =
            usize::try_from(protocol_settings.validators_count).map_err(|_| {
                ChainSpecError::InvalidValidatorCount {
                    validators_count: protocol_settings.validators_count,
                    committee_len: protocol_settings.standby_committee.len(),
                }
            })?;
        if validators_count == 0 || validators_count > protocol_settings.standby_committee.len() {
            return Err(ChainSpecError::InvalidValidatorCount {
                validators_count: protocol_settings.validators_count,
                committee_len: protocol_settings.standby_committee.len(),
            });
        }
        if genesis.validators.len() != validators_count {
            return Err(ChainSpecError::GenesisValidatorMismatch {
                genesis_validators: genesis.validators.len(),
                protocol_validators: validators_count,
            });
        }
        if genesis.committee.len() != protocol_settings.standby_committee.len() {
            return Err(ChainSpecError::GenesisCommitteeSizeMismatch {
                genesis_committee: genesis.committee.len(),
                protocol_committee: protocol_settings.standby_committee.len(),
            });
        }
        validate_committee(&genesis, &protocol_settings)?;
        validate_genesis_validators(&genesis, &protocol_settings, validators_count)?;

        Ok(Self {
            identity: ChainIdentity {
                name,
                network_type,
                network_magic: protocol_settings.network,
                expected_genesis_hash,
            },
            protocol_settings: Arc::new(protocol_settings),
            genesis: Arc::new(genesis),
        })
    }

    /// Returns the canonical Neo N3 v3.10.1 MainNet specification.
    pub fn mainnet() -> Result<Arc<Self>, ChainSpecError> {
        let protocol = ProtocolSettings::try_mainnet().map_err(ChainSpecError::InvalidProtocol)?;
        let genesis_hash = UInt256::parse(MAINNET_GENESIS_HASH)
            .map_err(|error| ChainSpecError::InvalidGenesisHash(error.to_string()))?;
        Self::build(
            "neo-n3-mainnet",
            NetworkType::MainNet,
            protocol,
            GenesisConfig::mainnet(),
            Some(genesis_hash),
        )
        .map(Arc::new)
    }

    /// Returns the canonical Neo N3 v3.10.1 TestNet specification.
    pub fn testnet() -> Result<Arc<Self>, ChainSpecError> {
        let protocol = ProtocolSettings::try_testnet().map_err(ChainSpecError::InvalidProtocol)?;
        let genesis_hash = UInt256::parse(TESTNET_GENESIS_HASH)
            .map_err(|error| ChainSpecError::InvalidGenesisHash(error.to_string()))?;
        Self::build(
            "neo-n3-testnet",
            NetworkType::TestNet,
            protocol,
            GenesisConfig::testnet(),
            Some(genesis_hash),
        )
        .map(Arc::new)
    }

    /// Selects a built-in chain. Private chains must provide a complete spec.
    pub fn from_network_type(network_type: NetworkType) -> Result<Arc<Self>, ChainSpecError> {
        match network_type {
            NetworkType::MainNet => Self::mainnet(),
            NetworkType::TestNet => Self::testnet(),
            NetworkType::Private => Err(ChainSpecError::PrivateSpecRequired),
        }
    }

    /// Stable chain identity used by storage and checkpoint binding.
    #[must_use]
    pub const fn identity(&self) -> &ChainIdentity {
        &self.identity
    }

    /// Neo network magic.
    #[must_use]
    pub const fn network_magic(&self) -> u32 {
        self.identity.network_magic()
    }

    /// Address version used by this chain.
    #[must_use]
    pub fn address_version(&self) -> u8 {
        self.protocol_settings.address_version
    }

    /// Immutable protocol settings used by existing lower-level Neo APIs.
    #[must_use]
    pub fn protocol_settings(&self) -> &ProtocolSettings {
        &self.protocol_settings
    }

    /// Shared protocol settings for lower-level APIs that retain an `Arc`.
    #[must_use]
    pub fn protocol_settings_arc(&self) -> Arc<ProtocolSettings> {
        Arc::clone(&self.protocol_settings)
    }

    /// Genesis inputs bound to this chain.
    #[must_use]
    pub fn genesis(&self) -> &GenesisConfig {
        &self.genesis
    }

    /// Ordered hardfork schedule.
    #[must_use]
    pub fn hardforks(&self) -> &HardforkSchedule {
        &self.protocol_settings.hardforks
    }

    /// Returns the configured activation height for `hardfork`.
    #[must_use]
    pub fn hardfork_activation(&self, hardfork: Hardfork) -> Option<u32> {
        self.hardforks().activation_height(hardfork)
    }

    /// Returns whether `hardfork` is active at `block_height`.
    #[must_use]
    pub fn is_hardfork_active(&self, hardfork: Hardfork, block_height: u32) -> bool {
        self.hardforks().is_active(hardfork, block_height)
    }

    /// Returns all active forks as an allocation-free bit set.
    #[must_use]
    pub fn active_hardforks(&self, block_height: u32) -> ActiveHardforks {
        self.hardforks().active_at(block_height)
    }

    /// Verifies the canonical genesis builder against this chain's identity pin.
    pub fn validate_genesis_hash(&self, actual: UInt256) -> Result<(), ChainSpecError> {
        if let Some(expected) = self.identity.expected_genesis_hash()
            && expected != actual
        {
            return Err(ChainSpecError::GenesisHashMismatch { expected, actual });
        }
        Ok(())
    }
}

/// Capability trait for components that own a concrete chain specification.
pub trait ChainSpecProvider: Send + Sync + 'static {
    /// Concrete chain-spec type retained by the provider.
    type ChainSpec: Send + Sync + 'static;

    /// Returns the provider's immutable chain specification.
    fn chain_spec(&self) -> Arc<Self::ChainSpec>;
}

impl ChainSpecProvider for Arc<NeoChainSpec> {
    type ChainSpec = NeoChainSpec;

    fn chain_spec(&self) -> Arc<Self::ChainSpec> {
        Arc::clone(self)
    }
}

fn validate_committee(
    genesis: &GenesisConfig,
    protocol_settings: &ProtocolSettings,
) -> Result<(), ChainSpecError> {
    for (index, (encoded, expected)) in genesis
        .committee
        .iter()
        .zip(&protocol_settings.standby_committee)
        .enumerate()
    {
        let actual =
            parse_public_key(encoded).map_err(|error| ChainSpecError::InvalidCommitteeKey {
                index,
                reason: error.to_string(),
            })?;
        if &actual != expected {
            return Err(ChainSpecError::GenesisCommitteeMismatch { index });
        }
    }
    Ok(())
}

fn validate_genesis_validators(
    genesis: &GenesisConfig,
    protocol_settings: &ProtocolSettings,
    validators_count: usize,
) -> Result<(), ChainSpecError> {
    for (index, (validator, expected)) in genesis
        .validators
        .iter()
        .zip(
            protocol_settings
                .standby_committee
                .iter()
                .take(validators_count),
        )
        .enumerate()
    {
        let actual = parse_public_key(&validator.public_key).map_err(|error| {
            ChainSpecError::InvalidCommitteeKey {
                index,
                reason: error.to_string(),
            }
        })?;
        if &actual != expected {
            return Err(ChainSpecError::GenesisCommitteeMismatch { index });
        }
    }
    Ok(())
}

#[cfg(test)]
#[path = "../tests/network/chain_spec.rs"]
mod tests;
