[package]
name = "neo-cryptography"
version = "0.3.0"
edition = "2021"
authors = ["R3E Network <jimmy@r3e.network>"]
description = "Cryptographic primitives for the Neo blockchain"
repository = "https://github.com/r3e-network/neo-rs"
license = "MIT"
readme = "README.md"

[dependencies]
# External dependencies
num-bigint = { workspace = true }
num-traits = { workspace = true }
secp256k1 = { workspace = true }
sha2 = { workspace = true }
ripemd = "0.1"
bs58 = "0.5"
hex = { workspace = true }
thiserror = { workspace = true }
derive_more = { workspace = true }
rand = { workspace = true }
rand_core = "0.5"
lazy_static = "1.4"
ed25519-dalek = "1.0"
serde = { workspace = true }

# Additional hash functions
sha1 = "0.10"
sha3 = "0.10"
md5 = "0.7"
blake2 = "0.10"

# ECDSA with secp256r1 (P-256)
p256 = { version = "0.13", features = ["ecdsa", "std", "expose-field", "ecdh"] }

# AES encryption
aes-gcm = "0.10"

# Internal dependencies
neo-config = { workspace = true }
# Temporarily commented out to break dependency cycle
# neo-io = { workspace = true, optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[features]
default = ["std"]
std = []
# Temporarily commented out to break dependency cycle
# io = ["neo-io"]

[[bench]]
name = "crypto_benchmarks"
harness = false
