# Copyright @ 2023 - 2024, R3E Network
# All Rights Reserved

refresh_rate: 60 seconds
appenders:
  rolling_file:
    kind: rolling_file
    path: "log/run.log"
    encoder:
      pattern: "[{d(%Y-%m-%dT%H:%M:%S%.6f)} {l} {M}:L{L}] {m}{n}"
    policy:
      trigger:
        kind: time
        interval: 1 day
      roller:
        kind: fixed_window
        pattern: "log/archive-run-{}.log"
        base: 0
        count: 128
root:
  level: info
  appenders:
    - rolling_file