[package]
name = "neo-type"
version = "0.1.0"
edition = "2021"

[dependencies]
neo-base   = { path = "../neo-base", default-features = false }
neo-crypto = { path = "../neo-crypto", default-features = false }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
hashbrown = "0.14.5"
bytes = "1.7.2"
hex              = { version = "0.4", default-features = false, features = ["alloc"] }
strum_macros = "0.26.4"
