[package]
name = "neo-wallets"
version = "0.1.0"
edition = "2021"
authors = ["Neo Global Development <dev@neo.org>"]
repository = "https://github.com/neo-project/neo-rs"
license = "MIT"
description = "Neo wallet implementation in Rust"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
derive_more = "0.99"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# Cryptography
scrypt = "0.11"
aes = "0.8"
cbc = "0.1"
rand = "0.8"
zeroize = { version = "1.7", features = ["derive"] }

# Encoding
hex = "0.4"
base64 = "0.21"
bs58 = "0.5"

# File handling
tempfile = "3.8"

# HTTP client
reqwest = { version = "0.11", features = ["json"] }

# Neo dependencies
neo-core = { path = "../core" }
neo-cryptography = { path = "../cryptography" }
neo-io = { path = "../io" }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"

[features]
default = []
