#[derive(Clone, Debug, PartialEq, Eq)]
pub enum Instruction {
    PushInt(i64),
    PushBool(bool),
    PushBytes(alloc::vec::Vec<u8>),
    Add,
    Sub,
    Mul,
    Div,
    And,
    Or,
    Not,
    Store(usize),
    Load(usize),
    Dup(usize),
    Swap(usize),
    Drop,
    Over,
    Pick(usize),
    Roll(usize),
    Mod,
    Equal,
    Greater,
    Less,
    GreaterOrEqual,
    LessOrEqual,
    NotEqual,
    Xor,
    Negate,
    Inc,
    Dec,
    Sign,
    Abs,
    Shl,
    Shr,
    ToBool,
    ToInt,
    ToBytes,
    ToString,
    Syscall(&'static str),
    Jump(usize),
    JumpIfFalse(usize),
    CallNative {
        contract: &'static str,
        method: &'static str,
        arg_count: usize,
    },
    Return,
}
