// Copyright @ 2023 - 2024, R3E Network
// All Rights Reserved

use strum::EnumIter;

use crate::*;

#[derive(Debug, Copy, Clone, Eq, PartialEq, EnumIter)]
#[repr(u8)]
pub enum OpCode {
    PushInt8   = 0x00,
    PushInt16  = 0x01,
    PushInt32  = 0x02,
    PushInt64  = 0x03,
    PushInt128 = 0x04,
    PushInt256 = 0x05,

    PushTrue   = 0x08,
    PushFalse  = 0x09,
    PushA      = 0x0A,
    PushNull   = 0x0B,
    PushData1  = 0x0C,
    PushData2  = 0x0D,
    PushData4  = 0x0E,

    PushM1     = 0x0F,
    Push0      = 0x10,
    Push1      = 0x11,
    Push2      = 0x12,
    Push3      = 0x13,
    Push4      = 0x14,
    Push5      = 0x15,
    Push6      = 0x16,
    Push7      = 0x17,
    Push8      = 0x18,
    Push9      = 0x19,
    Push10     = 0x1A,
    Push11     = 0x1B,
    Push12     = 0x1C,
    Push13     = 0x1D,
    Push14     = 0x1E,
    Push15     = 0x1F,
    Push16     = 0x20,

    Nop        = 0x21,
    Jmp        = 0x22,
    JmpL       = 0x23,
    JmpIf      = 0x24,
    JmpIfL     = 0x25,
    JmpIfNot   = 0x26,
    JmpIfNotL  = 0x27,
    JmpEq      = 0x28,
    JmpEqL     = 0x29,
    JmpNe      = 0x2A,
    JmpNeL     = 0x2B,
    JmpGt      = 0x2C,
    JmpGtL     = 0x2D,
    JmpGe      = 0x2E,
    JmpGeL     = 0x2F,
    JmpLt      = 0x30,
    JmpLtL     = 0x31,
    JmpLe      = 0x32,
    JmpLeL     = 0x33,

    Call       = 0x34,
    CallL      = 0x35,
    CallA      = 0x36,
    CallT      = 0x37,
    Abort      = 0x38,
    Assert     = 0x39,

    Throw      = 0x3A,
    Try        = 0x3B,
    TryL       = 0x3C,
    EndTry     = 0x3D,
    EndTryL    = 0x3E,
    EndFinally = 0x3F,

    Return     = 0x40,
    Syscall    = 0x41,

    Depth      = 0x43,
    Drop       = 0x45,
    Nip        = 0x46,
    Xdrop      = 0x48,
    Clear      = 0x49,
    Dup        = 0x4A,
    Over       = 0x4B,
    Pick       = 0x4D,
    Tuck       = 0x4E,

    Swap       = 0x50,
    Rotate     = 0x51,
    Roll       = 0x52,

    Reverse3   = 0x53,
    Reverse4   = 0x54,
    ReverseN   = 0x55,
    InitSSLot  = 0x56,
    InitSlot   = 0x57,

    LdSFLd0    = 0x58,
    LdSFLd1    = 0x59,
    LdSFLd2    = 0x5A,
    LdSFLd3    = 0x5B,
    LdSFLd4    = 0x5C,
    LdSFLd5    = 0x5D,
    LdSFLd6    = 0x5E,
    LdSFLd     = 0x5F,

    StSFLd0    = 0x60,
    StSFLd1    = 0x61,
    StSFLd2    = 0x62,
    StSFLd3    = 0x63,
    StSFLd4    = 0x64,
    StSFLd5    = 0x65,
    StSFLd6    = 0x66,
    StSFLd     = 0x67,

    LdLoc0     = 0x68,
    LdLoc1     = 0x69,
    LdLoc2     = 0x6A,
    LdLoc3     = 0x6B,
    LdLoc4     = 0x6C,
    LdLoc5     = 0x6D,
    LdLoc6     = 0x6E,
    LdLoc      = 0x6F,

    StLoc0     = 0x70,
    StLoc1     = 0x71,
    StLoc2     = 0x72,
    StLoc3     = 0x73,
    StLoc4     = 0x74,
    StLoc5     = 0x75,
    StLoc6     = 0x76,
    StLoc      = 0x77,

    LdArg0     = 0x78,
    LdArg1     = 0x79,
    LdArg2     = 0x7A,
    LdArg3     = 0x7B,
    LdArg4     = 0x7C,
    LdArg5     = 0x7D,
    LdArg6     = 0x7E,
    LdArg      = 0x7F,

    StArg0     = 0x80,
    StArg1     = 0x81,
    StArg2     = 0x82,
    StArg3     = 0x83,
    StArg4     = 0x84,
    StArg5     = 0x85,
    StArg6     = 0x86,
    StArg      = 0x87,

    NewBuffer  = 0x88,
    MemCpy     = 0x89,
    Cat        = 0x8B,
    SubStr     = 0x8C,
    Left       = 0x8D,
    Right      = 0x8E,

    Invert     = 0x90,
    And        = 0x91,
    Or         = 0x92,
    Xor        = 0x93,
    Equal      = 0x97,
    NotEqual   = 0x98,
    Sign       = 0x99,
    Abs        = 0x9A,
    Negate     = 0x9B,

    Inc        = 0x9C,
    Dec        = 0x9D,
    Add        = 0x9E,
    Sub        = 0x9F,
    Mul        = 0xA0,
    Div        = 0xA1,
    Mod        = 0xA2,
    Pow        = 0xA3,
    Sqrt       = 0xA4,
    ModMul     = 0xA5,
    ModPow     = 0xA6,

    Shl        = 0xA8,
    Shr        = 0xA9,
    Not        = 0xAA,
    BoolAnd    = 0xAB,
    BoolOr     = 0xAC,

    Nz         = 0xB1,
    NumEqual   = 0xB3,
    NumNotEqual = 0xB4,
    Lt         = 0xB5,
    Le         = 0xB6,
    Gt         = 0xB7,
    Ge         = 0xB8,
    Min        = 0xB9,
    Max        = 0xBA,
    Within     = 0xBB,

    PackMap    = 0xBE,
    PackStruct = 0xBF,
    Pack       = 0xC0,
    Unpack     = 0xC1,

    NewArray0  = 0xC2,
    NewArray   = 0xC3,
    NewArrayT  = 0xC4,
    NewStruct0 = 0xC5,
    NewStruct  = 0xC6,
    NewMap     = 0xC8,

    Size       = 0xCA,
    HasKey     = 0xCB,
    Keys       = 0xCC,
    Values     = 0xCD,

    PickItem   = 0xCE,
    Append     = 0xCF,
    SetItem    = 0xD0,
    ReverseItems = 0xD1,
    Remove     = 0xD2,
    ClearItems = 0xD3,
    PopItem    = 0xD4,

    IsNull     = 0xD8,
    IsType     = 0xD9,
    Convert    = 0xDB,

    AbortMsg   = 0xE0,
    AssertMsg  = 0xE1,
}

#[derive(Debug, Copy, Clone)]
pub(crate) struct CodeAttr {
    pub price: u64,

    // data/address size after this OpCode
    pub trailing: u32,

    pub unsigned: bool,
    // pub may_jump: bool,
}

impl OpCode {
    #[inline]
    pub const fn as_u8(&self) -> u8 { *self as u8 }

    #[inline]
    pub const fn from_u8(code: u8) -> Option<OpCode> { OP_CODES[code as usize] }

    #[inline]
    pub const fn is_valid(code: u8) -> bool { OP_CODES[code as usize].is_some() }

    #[inline]
    pub(crate) const fn attr(&self) -> CodeAttr { CODE_ATTRS[*self as usize] }

    #[inline]
    pub(crate) fn as_op(&self, ip: u32) -> Op {
        Op { ip, code: *self, operand: Operand::default() }
    }

    #[inline]
    pub(crate) fn as_operand_op(&self, ip: u32, operand: Operand) -> Op {
        Op { ip, code: *self, operand }
    }
}

impl RunPrice for OpCode {
    #[inline]
    fn price(&self) -> u64 { self.attr().price }
}

// #[derive(Debug, Clone, EnumIter)]
// #[repr(u8)]
// pub enum Instruction {
//     PushInt8 { operand: i8 },       // = 0x00,
//     PushInt16 { operand: i16 },     // = 0x01,
//     PushInt32 { operand: i32 },     // = 0x02,
//     PushInt64 { operand: i64 },     // = 0x03,
//     PushInt128 { operand: i128 },   // = 0x04,
//     PushInt256 { operand: I256 },   // = 0x05,
//     PushTrue,                       // = 0x08,
//     PushFalse,                      // = 0x09,
//     PushA,                          // = 0x0A,
//     PushNull,                       // = 0x0B,
//     PushData1 { operand: Operand }, // = 0x0C,
//     PushData2 { operand: Operand }, // = 0x0D,
//     PushData4 { operand: Operand }, // = 0x0E,
//     PushM1,                         // = 0x0F,
//     Push0,                          // = 0x10,
//     Push1,                          // = 0x11,
//     Push2,                          // = 0x12,
//     Push3,                          // = 0x13,
//     Push4,                          // = 0x14,
//     Push5,                          // = 0x15,
//     Push6,                          // = 0x16,
//     Push7,                          // = 0x17,
//     Push8,                          // = 0x18,
//     Push9,                          // = 0x19,
//     Push10,                         // = 0x1A,
//     Push11,                         // = 0x1B,
//     Push12,                         // = 0x1C,
//     Push13,                         // = 0x1D,
//     Push14,                         // = 0x1E,
//     Push15,                         // = 0x1F,
//     Push16,                         // = 0x20,
//
//     Nop,                                 // = 0x21,
//     Jmp { operand: i8 },                 // = 0x22,
//     JmpL { operand: i32 },               // = 0x23,
//     JmpIf { operand: i8 },               // = 0x24,
//     JmpIfL { operand: i32 },             // = 0x25,
//     JmpIfNot { operand: i8 },            // = 0x26,
//     JmpIfNotL { operand: i32 },          // = 0x27,
//     JmpEq { operand: i8 },               // = 0x28,
//     JmpEqL { operand: i32 },             // = 0x29,
//     JmpNe { operand: i8 },               // = 0x2A,
//     JmpNeL { operand: i32 },             // = 0x2B,
//     JmpGt { operand: i8 },               // = 0x2C,
//     JmpGtL { operand: i32 },             // = 0x2D,
//     JmpGe { operand: i8 },               // = 0x2E,
//     JmpGeL { operand: i32 },             // = 0x2F,
//     JmpLt { operand: i8 },               // = 0x30,
//     JmpLtL { operand: i32 },             // = 0x31,
//     JmpLe { operand: i8 },               // = 0x32,
//     JmpLeL { operand: i32 },             // = 0x33,
//     Call { operand: i8 },                // = 0x34,
//     CallL { operand: i32 },              // = 0x35,
//     CallA,                               // = 0x36,
//     CallT { operand: u16 },              // = 0x37,
//     Abort,                               // = 0x38,
//     Assert,                              // = 0x39,
//     Throw,                               // = 0x3A,
//     Try { catch: i8, finally: i8 },      // = 0x3B,
//     TryL { operand: i32, finally: i32 }, // = 0x3C,
//     EndTry { operand: i8 },              // = 0x3D,
//     EndTryL { operand: i32 },            // = 0x3E,
//     EndFinally,                          // = 0x3F,
//     Return,                              // = 0x40,
//
//     Syscall { operand: u32 },         // = 0x41,
//     Depth,                            // = 0x43,
//     Drop,                             // = 0x45,
//     Nip,                              // = 0x46,
//     Xdrop,                            // = 0x48,
//     Clear,                            // = 0x49,
//     Dup,                              // = 0x4A,
//     Over,                             // = 0x4B,
//     Pick,                             // = 0x4D,
//     Tuck,                             // = 0x4E,
//     Swap,                             // = 0x50,
//     Rotate,                           // = 0x51,
//     Roll,                             // = 0x52,
//     Reverse3,                         // = 0x53,
//     Reverse4,                         // = 0x54,
//     ReverseN,                         // = 0x55,
//     InitSSLot { operand: u8 },        // = 0x56,
//     InitSlot { slots: u8, vars: u8 }, // = 0x57,
//
//     LdSFLd0,                // = 0x58,
//     LdSFLd1,                // = 0x59,
//     LdSFLd2,                // = 0x5A,
//     LdSFLd3,                // = 0x5B,
//     LdSFLd4,                // = 0x5C,
//     LdSFLd5,                // = 0x5D,
//     LdSFLd6,                // = 0x5E,
//     LdSFLd { operand: u8 }, // = 0x5F,
//     StSFLd0,                // = 0x60,
//     StSFLd1,                // = 0x61,
//     StSFLd2,                // = 0x62,
//     StSFLd3,                // = 0x63,
//     StSFLd4,                // = 0x64,
//     StSFLd5,                // = 0x65,
//     StSFLd6,                // = 0x66,
//     StSFLd { operand: u8 }, // = 0x67,
//     LdLoc0,                 // = 0x68,
//     LdLoc1,                 // = 0x69,
//     LdLoc2,                 // = 0x6A,
//     LdLoc3,                 // = 0x6B,
//     LdLoc4,                 // = 0x6C,
//     LdLoc5,                 // = 0x6D,
//     LdLoc6,                 // = 0x6E,
//     LdLoc { operand: u8 },  // = 0x6F,
//     StLoc0,                 // = 0x70,
//     StLoc1,                 // = 0x71,
//     StLoc2,                 // = 0x72,
//     StLoc3,                 // = 0x73,
//     StLoc4,                 // = 0x74,
//     StLoc5,                 // = 0x75,
//     StLoc6,                 // = 0x76,
//     StLoc { operand: u8 },  // = 0x77,
//     LdArg0,                 // = 0x78,
//     LdArg1,                 // = 0x79,
//     LdArg2,                 // = 0x7A,
//     LdArg3,                 // = 0x7B,
//     LdArg4,                 // = 0x7C,
//     LdArg5,                 // = 0x7D,
//     LdArg6,                 // = 0x7E,
//     LdArg { operand: u8 },  // = 0x7F,
//     StArg0,                 // = 0x80,
//     StArg1,                 // = 0x81,
//     StArg2,                 // = 0x82,
//     StArg3,                 // = 0x83,
//     StArg4,                 // = 0x84,
//     StArg5,                 // = 0x85,
//     StArg6,                 // = 0x86,
//     StArg { operand: u8 },  // = 0x87,
//
//     NewBuffer,                 // = 0x88,
//     MemCpy,                    // = 0x89,
//     Cat,                       // = 0x8B,
//     SubStr,                    // = 0x8C,
//     Left,                      // = 0x8D,
//     Right,                     // = 0x8E,
//     Invert,                    // = 0x90,
//     And,                       // = 0x91,
//     Or,                        // = 0x92,
//     Xor,                       // = 0x93,
//     Equal,                     // = 0x97,
//     NotEqual,                  // = 0x98,
//     Sign,                      // = 0x99,
//     Abs,                       // = 0x9A,
//     Negate,                    // = 0x9B,
//     Inc,                       // = 0x9C,
//     Dec,                       // = 0x9D,
//     Add,                       // = 0x9E,
//     Sub,                       // = 0x9F,
//     Mul,                       // = 0xA0,
//     Div,                       // = 0xA1,
//     Mod,                       // = 0xA2,
//     Pow,                       // = 0xA3,
//     Sqrt,                      // = 0xA4,
//     ModMul,                    // = 0xA5,
//     ModPow,                    // = 0xA6,
//     Shl,                       // = 0xA8,
//     Shr,                       // = 0xA9,
//     Not,                       // = 0xAA,
//     BoolAnd,                   // = 0xAB,
//     BoolOr,                    // = 0xAC,
//     Nz,                        // = 0xB1,
//     NumEqual,                  // = 0xB3,
//     NumNotEqual,               // = 0xB4,
//     Lt,                        // = 0xB5,
//     Le,                        // = 0xB6,
//     Gt,                        // = 0xB7,
//     Ge,                        // = 0xB8,
//     Min,                       // = 0xB9,
//     Max,                       // = 0xBA,
//     Within,                    // = 0xBB,
//     PackMap,                   // = 0xBE,
//     PackStruct,                // = 0xBF,
//     Pack,                      // = 0xC0,
//     Unpack,                    // = 0xC1,
//     NewArray0,                 // = 0xC2,
//     NewArray,                  // = 0xC3,
//     NewArrayT { operand: u8 }, // = 0xC4,
//     NewStruct0,                // = 0xC5,
//     NewStruct,                 // = 0xC6,
//     NewMap,                    // = 0xC8,
//     Size,                      // = 0xCA,
//     HasKey,                    // = 0xCB,
//     Keys,                      // = 0xCC,
//     Values,                    // = 0xCD,
//     PickItem,                  // = 0xCE,
//     Append,                    // = 0xCF,
//     SetItem,                   // = 0xD0,
//     ReverseItems,              // = 0xD1,
//     Remove,                    // = 0xD2,
//     ClearItems,                // = 0xD3,
//     PopItem,                   // = 0xD4,
//     IsNull,                    // = 0xD8,
//     IsType { operand: u8 },    // = 0xD9,
//     Convert { operand: u8 },   // = 0xDB,
//     AbortMsg,                  // = 0xE0,
//     AssertMsg,                 // = 0xE1,
// }
