name: Feature request
description: Suggest an enhancement for neo-rs
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please include enough context so we can understand the use case.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see changed or added?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem does this solve? Who benefits?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you tried or rejected
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links to related issues, specs, or references
      validations:
        required: false
