# Copyright @ 2023 - 2024, R3E Network
# All Rights Reserved

[package]
name = "neo"
version = "0.1.0"
edition = "2021"


[workspace]
members = []


[dependencies]
neo-base     = { path = "../neo-base" }
neo-p2p      = { path = "../neo-p2p" }

log          = { version = "0.4" }
log4rs       = { version = "1.3" }

signal-hook  = { version = "0.3" }
clap         = { version = "4.5", features = ["derive"] }

anyhow       = { version = "1" }
duration-str = { version = "0.11", default-features = false, features = ["serde"] }

serde        = { version = "1", default-features = false, features = ["derive", "alloc"] }
serde_yaml   = { version = "0.9" }


[profile.release]
lto           = "fat"
opt-level     = 3
codegen-units = 1

# RUSTFLAGS     = "-C target-cpu=native"