import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]

SPLIT_ENTRYPOINT_PATHS = (
    "neo-indexer/src/indexer.rs",
    "neo-indexer/src/indexer/tests.rs",
    "neo-indexer/src/service.rs",
    "neo-indexer/src/service/tests.rs",
    "neo-blockchain/src/handlers.rs",
    "neo-blockchain/src/handlers/tests.rs",
    "neo-blockchain/src/handlers/transactions.rs",
    "neo-blockchain/src/handlers/tests/block_flow.rs",
    "neo-blockchain/src/handlers/tests/extensible_headers.rs",
    "neo-blockchain/src/handlers/tests/transactions.rs",
    "neo-blockchain/src/native_persist.rs",
    "neo-blockchain/src/native_persist/tests.rs",
    "neo-consensus/src/service/tests/prepare.rs",
    "neo-consensus/src/service/tests/prepare/backup_request.rs",
    "neo-consensus/src/service/tests/prepare/commit_flow.rs",
    "neo-consensus/src/service/tests/prepare/initial_round.rs",
    "neo-consensus/src/service/tests/prepare/primary_proposal.rs",
    "neo-consensus/src/service/tests/prepare/response_and_cache.rs",
    "neo-crypto/src/ecc.rs",
    "neo-crypto/src/ecc/tests.rs",
    "neo-crypto/src/mpt_trie/tests.rs",
    "neo-crypto/src/mpt_trie/tests/cache.rs",
    "neo-crypto/src/mpt_trie/tests/diagnostics.rs",
    "neo-crypto/src/mpt_trie/tests/find_limited.rs",
    "neo-crypto/src/mpt_trie/tests/node.rs",
    "neo-crypto/src/mpt_trie/tests/trie.rs",
    "neo-crypto/src/mpt_trie/trie.rs",
    "neo-crypto/src/mpt_trie/trie/proof.rs",
    "neo-execution/src/application_engine/contracts.rs",
    "neo-execution/src/application_engine/contracts/tests.rs",
    "neo-execution/src/application_engine/state.rs",
    "neo-execution/src/application_engine/state/tests.rs",
    "neo-execution/src/native_contract.rs",
    "neo-execution/src/native_contract/tests.rs",
    "neo-execution/src/application_engine_runtime.rs",
    "neo-execution/src/application_engine_runtime/tests.rs",
    "neo-manifest/src/manifest/contract_manifest.rs",
    "neo-manifest/src/manifest/contract_manifest/tests.rs",
    "neo-mempool/src/memory_pool.rs",
    "neo-mempool/src/memory_pool/tests.rs",
    "neo-native-contracts/src/contract_management.rs",
    "neo-native-contracts/src/contract_management/operations.rs",
    "neo-native-contracts/src/contract_management/tests.rs",
    "neo-native-contracts/src/contract_management/tests/deploy_update_engine_tests/mod.rs",
    "neo-native-contracts/src/contract_management/tests/deploy_update_engine_tests/fixtures.rs",
    "neo-native-contracts/src/contract_management/tests/deploy_update_engine_tests/deploy.rs",
    "neo-native-contracts/src/contract_management/tests/deploy_update_engine_tests/update.rs",
    "neo-native-contracts/src/contract_management/tests/destroy_engine_tests.rs",
    "neo-native-contracts/src/contract_management/tests/persist_tests.rs",
    "neo-native-contracts/src/contract_management/tests/tests.rs",
    "neo-native-contracts/src/gas_token.rs",
    "neo-native-contracts/src/gas_token/tests.rs",
    "neo-native-contracts/src/tests.rs",
    "neo-native-contracts/src/ledger_contract.rs",
    "neo-native-contracts/src/ledger_contract/tests.rs",
    "neo-native-contracts/src/neo_token/tests.rs",
    "neo-native-contracts/src/neo_token.rs",
    "neo-native-contracts/src/neo_token/metadata.rs",
    "neo-native-contracts/src/neo_token/storage/mod.rs",
    "neo-native-contracts/src/neo_token/transfers.rs",
    "neo-native-contracts/src/neo_token/tests/basic_tests.rs",
    "neo-native-contracts/src/neo_token/tests/committee_recompute_tests.rs",
    "neo-native-contracts/src/neo_token/tests/governance_writer_tests.rs",
    "neo-native-contracts/src/neo_token/tests/persist_hook_tests.rs",
    "neo-native-contracts/src/neo_token/tests/storage_codec_tests.rs",
    "neo-native-contracts/src/neo_token/tests/witness_harness_tests.rs",
    "neo-native-contracts/src/notary.rs",
    "neo-native-contracts/src/notary/tests.rs",
    "neo-native-contracts/src/notary/verify_dispatch_tests.rs",
    "neo-native-contracts/src/oracle_contract.rs",
    "neo-native-contracts/src/oracle_contract/oracle_native_tests.rs",
    "neo-native-contracts/src/oracle_contract/oracle_request_finish_tests.rs",
    "neo-native-contracts/src/policy_contract.rs",
    "neo-native-contracts/src/policy_contract/metadata.rs",
    "neo-native-contracts/src/policy_contract/storage.rs",
    "neo-native-contracts/src/policy_contract/tests.rs",
    "neo-native-contracts/src/policy_contract/tests/policy_writer_tests.rs",
    "neo-native-contracts/src/policy_contract/tests/surface.rs",
    "neo-native-contracts/src/policy_contract/tests/policy_writer_tests/block_account.rs",
    "neo-native-contracts/src/policy_contract/tests/policy_writer_tests/recover_fund.rs",
    "neo-native-contracts/src/policy_contract/tests/policy_writer_tests/whitelist.rs",
    "neo-native-contracts/src/policy_contract/tests/tests.rs",
    "neo-native-contracts/src/std_lib.rs",
    "neo-native-contracts/src/std_lib/tests.rs",
    "neo-native-contracts/tests/native_manifest_pinning/mod.rs",
    "neo-native-contracts/tests/native_manifest_pinning/contract_manifests.rs",
    "neo-native-contracts/tests/native_manifest_pinning/fungible_and_policy.rs",
    "neo-native-contracts/tests/native_manifest_pinning/handles_and_catalog.rs",
    "neo-native-contracts/tests/native_manifest_pinning/method_metadata.rs",
    "neo-native-contracts/tests/native_manifest_pinning/safe_flags.rs",
    "neo-network/tests/handshake/mod.rs",
    "neo-network/tests/handshake/block_source.rs",
    "neo-network/tests/handshake/handshake_flow.rs",
    "neo-network/tests/handshake/inventory.rs",
    "neo-network/tests/handshake/limits.rs",
    "neo-network/tests/handshake/rejections.rs",
    "neo-network/tests/handshake/sync_runtime.rs",
    "neo-network/tests/handshake/sync_runtime/lifecycle.rs",
    "neo-network/tests/handshake/sync_runtime/range_fetch.rs",
    "neo-network/src/remote_node.rs",
    "neo-network/src/remote_node/session.rs",
    "neo-network/src/remote_node/session/messages.rs",
    "neo-node/src/consensus.rs",
    "neo-primitives/src/macros.rs",
    "neo-primitives/src/macros/display_hex.rs",
    "neo-primitives/src/macros/message_flags.rs",
    "neo-primitives/src/macros/p2p_message_command.rs",
    "neo-primitives/src/macros/protocol_enum.rs",
    "neo-primitives/src/macros/uint.rs",
    "neo-rpc/src/client/rpc_client/tests.rs",
    "neo-rpc/src/client/rpc_client/tests/blockchain_basic.rs",
    "neo-rpc/src/client/rpc_client/tests/blockchain_verbose.rs",
    "neo-rpc/src/client/rpc_client/tests/node.rs",
    "neo-rpc/src/client/rpc_client/tests/transport.rs",
    "neo-rpc/src/client/rpc_client/tests/wallet.rs",
    "neo-rpc/src/client/rpc_client/tests/wallet_and_nep17.rs",
    "neo-rpc/src/client/utility/parsing.rs",
    "neo-rpc/src/client/utility/parsing/tests.rs",
    "neo-rpc/src/client/utility/tests.rs",
    "neo-rpc/src/server/rpc_server_blockchain/tests.rs",
    "neo-rpc/src/server/rpc_server_blockchain/tests/blocks.rs",
    "neo-rpc/src/server/rpc_server_blockchain/tests/contracts.rs",
    "neo-rpc/src/server/rpc_server_blockchain/tests/mempool.rs",
    "neo-rpc/src/server/rpc_server_blockchain/tests/native_and_errors.rs",
    "neo-rpc/src/server/rpc_server_blockchain/tests/storage.rs",
    "neo-rpc/src/server/rpc_server_blockchain/tests/transactions.rs",
    "neo-rpc/src/server/rpc_server_blockchain/tests/validators.rs",
    "neo-rpc/src/server/rpc_server_indexer.rs",
    "neo-rpc/src/server/rpc_server_indexer/tests.rs",
    "neo-rpc/src/server/rpc_server_node/tests.rs",
    "neo-rpc/src/server/rpc_server_node/tests/connection_count.rs",
    "neo-rpc/src/server/rpc_server_node/tests/get_peers.rs",
    "neo-rpc/src/server/rpc_server_node/tests/get_version.rs",
    "neo-rpc/src/server/rpc_server_node/tests/send_raw_transaction.rs",
    "neo-rpc/src/server/rpc_server_node/tests/submit_block.rs",
    "neo-rpc/src/server/smart_contract/tests.rs",
    "neo-rpc/src/server/smart_contract/tests/contract_verify.rs",
    "neo-rpc/src/server/smart_contract/tests/script_and_function_invocation.rs",
    "neo-rpc/src/server/smart_contract/tests/sessions.rs",
    "neo-rpc/src/server/smart_contract/tests/validation_errors.rs",
    "neo-rpc/src/server/smart_contract/tests/wallet_and_gas.rs",
    "neo-rpc/src/server/rpc_server_wallet/mod.rs",
    "neo-rpc/src/server/rpc_server_wallet/balance.rs",
    "neo-rpc/src/server/rpc_server_wallet/support.rs",
    "neo-rpc/src/server/rpc_server_wallet/tests.rs",
    "neo-rpc/src/server/rpc_server_wallet/tests/cancel_transaction.rs",
    "neo-rpc/src/server/rpc_server_wallet/tests/lifecycle.rs",
    "neo-rpc/src/server/rpc_server_wallet/tests/network_fee.rs",
    "neo-rpc/src/server/rpc_server_wallet/tests/send_from.rs",
    "neo-rpc/src/server/rpc_server_wallet/tests/send_many.rs",
    "neo-rpc/src/server/rpc_server_wallet/tests/send_to_address.rs",
    "neo-state-service/src/mpt_store.rs",
    "neo-state-service/src/mpt_store/tests.rs",
    "neo-vm/src/jump_table/compound.rs",
    "neo-vm/src/jump_table/compound/before543.rs",
    "neo-vm/src/stack_item/stack_item.rs",
    "neo-vm/src/stack_item/stack_item/equality.rs",
    "neo-vm/src/stack_item/stack_item/tests.rs",
    "neo-node/src/consensus/hsm.rs",
    "neo-node/src/consensus/proposal.rs",
    "neo-node/src/consensus/tests.rs",
    "neo-node/src/consensus/tests/proposal.rs",
    "neo-node/src/node.rs",
    "neo-node/src/node/config.rs",
    "neo-node/src/node/indexer_runtime.rs",
    "neo-node/src/node/indexer_runtime/tests.rs",
    "neo-node/src/node/ledger_source.rs",
    "neo-node/src/node/config/validation.rs",
    "neo-node/src/node/tests.rs",
    "neo-node/src/node/tests/config_parsing.rs",
    "neo-node/src/node/tests/config_validation.rs",
    "neo-node/src/node/tests/runtime.rs",
)

HIGH_CHURN_PROTOCOL_TEST_PATHS = (
    "neo-native-contracts/src/policy_contract/tests/policy_writer_tests.rs",
    "neo-native-contracts/src/policy_contract/tests/policy_writer_tests/block_account.rs",
    "neo-native-contracts/src/policy_contract/tests/policy_writer_tests/recover_fund.rs",
    "neo-native-contracts/src/policy_contract/tests/policy_writer_tests/whitelist.rs",
)


def assert_paths_under(test_case, relative_paths, max_lines, message):
    for relative in relative_paths:
        path = REPO_ROOT / relative
        with test_case.subTest(path=relative):
            if not path.exists():
                # This catalog intentionally tracks modules that have been split
                # over time. Once a path is moved/deleted by a layout cleanup,
                # repository-hygiene tests enforce the new folder structure.
                continue
            line_count = len(path.read_text(encoding="utf-8").splitlines())
            test_case.assertLessEqual(line_count, max_lines, message.format(path=relative))


class FileSizeCatalogLimitTests(unittest.TestCase):
    def test_node_entrypoint_and_split_tests_stay_below_1000_lines(self):
        assert_paths_under(
            self,
            SPLIT_ENTRYPOINT_PATHS,
            1000,
            "{path} should stay focused; split large modules before they grow past 1000 lines",
        )

    def test_high_churn_protocol_tests_keep_review_headroom(self):
        assert_paths_under(
            self,
            HIGH_CHURN_PROTOCOL_TEST_PATHS,
            900,
            "{path} should split high-churn protocol regressions into focused modules",
        )


if __name__ == "__main__":
    unittest.main()
