[build]
# Optimize for production (disabled for development builds to avoid LTO conflicts)
# rustflags = ["-C", "opt-level=3", "-C", "lto=true", "-C", "codegen-units=1"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.production]
inherits = "release"
lto = "fat"
opt-level = 3
codegen-units = 1
