# Clippy configuration for Neo-RS
# See https://doc.rust-lang.org/clippy/configuration.html for all options

# === Cognitive complexity ===
# Allow slightly higher complexity for blockchain operations
cognitive-complexity-threshold = 30

# === Documentation ===
# Note: missing-docs-in-private-items is not a valid clippy configuration option

# === Performance ===
# Large types that should be boxed (in bytes)
type-complexity-threshold = 250
trivial-copy-size-limit = 128

# === Style preferences ===
# Maximum number of lines for single expressions
single-char-binding-names-threshold = 5

# === Blockchain-specific allowances ===
# Allow longer function names for descriptive blockchain operations
max-fn-params-bools = 3

# Allow some complexity in VM operations
too-many-arguments-threshold = 8

# === Literal thresholds ===
# Allow larger arrays for cryptographic constants
array-size-threshold = 512000

# === Error handling ===
# Don't warn about Result types in certain contexts
avoid-breaking-exported-api = true