[package]
name = "simple-neo-node"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
serde = "1.0"
serde_json = "1.0"

# Network dependencies
socket2 = "0.5"
trust-dns-resolver = "0.23"

[[bin]]
name = "neo-testnet"
path = "src/main.rs"