[package]
name = "neo-ledger"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
thiserror = "1.0"
derive_more = "0.99"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"

# Logging
tracing = "0.1"

# Cryptography
sha2 = "0.10"
ripemd = "0.1"
p256 = { version = "0.13", features = ["ecdsa", "std"] }
signature = "2.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Collections and utilities
indexmap = "2.0"
dashmap = "5.5"
parking_lot = "0.12"
rand = "0.8"
hex = "0.4"
num-bigint = "0.4"
num-traits = "0.2"

# Database
rocksdb = "0.21"

# Neo dependencies
neo-core = { path = "../core" }
neo-cryptography = { path = "../cryptography" }
neo-io = { path = "../io" }
neo-vm = { path = "../vm" }
neo-config = { path = "../config" }
neo-persistence = { path = "../persistence" }
# neo-smart-contract = { path = "../smart_contract" } # Circular dependency

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
