[package]
name = "neo-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.40.0"
log = "0.4.22"
rand = "0.9.0-alpha.2"
num-bigint = "0.4.6"
chrono = "0.4.38"
num-traits = "0.2.19"
