#!/usr/bin/env python3
"""Prepare an isolated bounded MainNet replay workspace from a checkpoint."""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path
from typing import Any


DEFAULT_NODE_BIN = "target/release/neo-node"
DEFAULT_PROBE_BIN = "target/debug/neo-db-probe"
DEFAULT_REFERENCE_RPC = "http://seed1.neo.org:10332"
DEFAULT_WORK_ROOT = "data/bounded-replay"
DEFAULT_RPC_PORT = 21332
DEFAULT_P2P_PORT = 21333
DEFAULT_METRICS_PORT = 21990


def parse_checkpoint_info(path: Path) -> dict[str, str]:
    info_path = path / "CHECKPOINT_INFO"
    if not info_path.exists():
        return {}
    info: dict[str, str] = {}
    for line in info_path.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.strip().startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        info[key.strip()] = value.strip()
    return info


def resolve_state_checkpoint(checkpoint: Path, info: dict[str, str]) -> Path | None:
    candidates: list[Path] = []
    if info.get("mpt_dir"):
        mpt_path = Path(info["mpt_dir"])
        candidates.append(mpt_path if mpt_path.is_absolute() else checkpoint / mpt_path)
        candidates.append(mpt_path)
    candidates.extend([checkpoint / "mpt", checkpoint / "state", checkpoint / "Data_MPT"])
    for candidate in candidates:
        if candidate.is_dir() and (candidate / "CURRENT").exists():
            return candidate
    return None


def toml_quote(value: Path | str) -> str:
    text = str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_config(
    *,
    chain_db: Path,
    state_db: Path,
    state_enabled: bool,
    rpc_port: int,
    p2p_port: int,
    metrics_port: int,
    log_file: Path,
) -> str:
    state_enabled_value = "true" if state_enabled else "false"
    return f"""# Generated by scripts/prepare-bounded-mainnet-replay.py.
[network]
network_type = "MainNet"
network_magic = 0x334F454E

[storage]
backend = "rocksdb"
path = {toml_quote(chain_db)}
read_only = false

[p2p]
port = {p2p_port}
max_connections = 20
min_desired_connections = 4
max_connections_per_address = 3
max_known_hashes = 1000
seed_nodes = [
    "seed1.neo.org:10333",
    "seed2.neo.org:10333",
    "seed3.neo.org:10333",
    "seed4.neo.org:10333",
    "seed5.neo.org:10333"
]
enable_compression = true
broadcast_history_limit = 100000

[rpc]
enabled = true
port = {rpc_port}
bind_address = "127.0.0.1"
cors_enabled = false
auth_enabled = false
disabled_methods = ["openwallet"]

[indexer]
enabled = false
backfill_on_startup = false
store_path = {toml_quote(chain_db / "indexer")}

[application_logs]
enabled = false
path = {toml_quote(chain_db / "application-logs")}
debug = false
exception_policy = "Ignore"

[tokens_tracker]
enabled = false
db_path = {toml_quote(chain_db / "tokens")}
track_history = false
max_results = 1000
enabled_trackers = ["NEP-17", "NEP-11"]
exception_policy = "StopPlugin"

[consensus]
enabled = false
auto_start = false

[telemetry]
[telemetry.metrics]
enabled = false
port = {metrics_port}
bind_address = "127.0.0.1"
path = "/metrics"

[observability]
enabled = false
service_name = "neo-node-bounded-replay"
environment = "validation"
capture_panics = true

[logging]
level = "info"
format = "json"
console_output = false
file_path = {toml_quote(log_file)}
max_file_size = "100MB"
max_files = 3

[blockchain]
block_time = 15000
max_transactions_per_block = 200

[state_service]
enabled = {state_enabled_value}
path = {toml_quote(state_db)}
full_state = true

[mempool]
max_transactions = 50000
"""


def step_by_name(plan: dict, name: str) -> dict:
    for step in plan.get("steps", []):
        if step.get("name") == name:
            return step
    raise KeyError(f"plan is missing step: {name}")


def build_replay_plan(
    *,
    checkpoint: Path,
    work_root: Path,
    label: str,
    start_height: int | None = None,
    target_height: int,
    addresses: list[str],
    node_bin: Path = Path(DEFAULT_NODE_BIN),
    probe_bin: Path = Path(DEFAULT_PROBE_BIN),
    reference_rpc: str = DEFAULT_REFERENCE_RPC,
    rpc_port: int = DEFAULT_RPC_PORT,
    p2p_port: int = DEFAULT_P2P_PORT,
    metrics_port: int = DEFAULT_METRICS_PORT,
) -> dict:
    checkpoint = checkpoint.resolve()
    work_dir = (work_root / label).resolve()
    chain_source = checkpoint / "data"
    info = parse_checkpoint_info(checkpoint)
    if start_height is None and info.get("height"):
        start_height = int(info["height"])
    state_source = resolve_state_checkpoint(checkpoint, info)
    state_present = state_source is not None
    validator_enabled = state_present and start_height is not None
    chain_db = work_dir / "data"
    state_db = work_dir / "mpt"
    config_path = work_dir / "neo-bounded-replay.toml"
    log_file = work_dir / "neo-node.log"
    status_file = work_dir / "stateroot-validation.json"
    resume_file = work_dir / "stateroot-last-validated"
    mode = "full-state" if state_present else "storage-sample"

    address_args = []
    for address in addresses:
        address_args.extend(["--address", address])

    validator_command = [
        "python3",
        "scripts/continuous-stateroot-validation.py",
        "--local-config",
        str(config_path),
        "--stop-at",
        str(target_height),
        "--status-file",
        str(status_file),
        "--resume-file",
        str(resume_file),
    ]
    if start_height is not None:
        validator_command[4:4] = ["--start", str(start_height)]

    replay_with_repairs_command = [
        "python3",
        "scripts/run-bounded-replay-with-repairs.py",
        "--config",
        str(config_path),
        "--db",
        str(chain_db),
        "--log",
        str(log_file),
        "--target-height",
        str(target_height),
        "--node-bin",
        str(node_bin),
        "--probe-bin",
        str(probe_bin),
        "--rpc",
        f"http://127.0.0.1:{rpc_port}",
        "--reference-rpc",
        reference_rpc,
    ]

    steps: list[dict[str, Any]] = [
        {
            "name": "copy-chain-checkpoint",
            "source": str(chain_source),
            "destination": str(chain_db),
            "required": True,
        },
        {
            "name": "copy-state-checkpoint",
            "source": str(state_source) if state_source else None,
            "destination": str(state_db),
            "required": state_present,
            "enabled": state_present,
        },
        {
            "name": "write-config",
            "path": str(config_path),
        },
        {
            "name": "node-preflight",
            "command": [str(node_bin), "--config", str(config_path), "--check-all"],
        },
        {
            "name": "run-node",
            "command": [str(node_bin), "--config", str(config_path)],
            "log": str(log_file),
        },
        {
            "name": "run-node-with-repairs",
            "command": replay_with_repairs_command,
            "log": str(log_file),
        },
        {
            "name": "state-root-validator",
            "enabled": validator_enabled,
            "command": validator_command,
            "reason": state_root_validator_disabled_reason(
                state_present=state_present,
                start_height=start_height,
            ),
        },
        {
            "name": "offline-gas-compare",
            "command": [
                "python3",
                "scripts/compare-offline-gas-storage.py",
                "--db",
                str(chain_db),
                "--probe-bin",
                str(probe_bin),
                "--reference-rpc",
                reference_rpc,
                *address_args,
            ],
        },
    ]

    return {
        "mode": mode,
        "checkpoint": {
            "path": str(checkpoint),
            "label": info.get("label"),
            "info": info,
        },
        "chain_checkpoint": {
            "path": str(chain_source),
            "present": chain_source.is_dir() and (chain_source / "CURRENT").exists(),
        },
        "state_checkpoint": {
            "path": str(state_source) if state_source else None,
            "present": state_present,
        },
        "work": {
            "root": str(work_root),
            "dir": str(work_dir),
            "chain_db": str(chain_db),
            "state_db": str(state_db),
            "config_path": str(config_path),
            "log_file": str(log_file),
            "status_file": str(status_file),
            "resume_file": str(resume_file),
        },
        "target_height": target_height,
        "start_height": start_height,
        "rpc_port": rpc_port,
        "p2p_port": p2p_port,
        "metrics_port": metrics_port,
        "steps": steps,
        "config_text": render_config(
            chain_db=chain_db,
            state_db=state_db,
            state_enabled=state_present,
            rpc_port=rpc_port,
            p2p_port=p2p_port,
            metrics_port=metrics_port,
            log_file=log_file,
        ),
    }


def copy_checkpoint_dir(source: Path, destination: Path) -> None:
    if not source.is_dir():
        raise FileNotFoundError(f"checkpoint source is missing: {source}")
    shutil.copytree(source, destination)


def state_root_validator_disabled_reason(
    *,
    state_present: bool,
    start_height: int | None,
) -> str | None:
    if not state_present:
        return "Checkpoint has no StateRoot/MPT directory; use storage-sample mode until a full-state checkpoint is available."
    if start_height is None:
        return "Checkpoint start height is unknown; pass --start-height so state-root validation starts at the checkpoint height."
    return None


def prepare_workspace(plan: dict, *, force: bool = False) -> dict:
    work_dir = Path(plan["work"]["dir"])
    if work_dir.exists():
        if not force:
            raise FileExistsError(f"work directory already exists: {work_dir}")
        shutil.rmtree(work_dir)
    work_dir.mkdir(parents=True)

    copy_checkpoint_dir(
        Path(step_by_name(plan, "copy-chain-checkpoint")["source"]),
        Path(plan["work"]["chain_db"]),
    )
    state_step = step_by_name(plan, "copy-state-checkpoint")
    if state_step.get("enabled"):
        copy_checkpoint_dir(Path(state_step["source"]), Path(plan["work"]["state_db"]))

    config_path = Path(plan["work"]["config_path"])
    config_path.write_text(plan["config_text"], encoding="utf-8")
    return {
        "prepared": True,
        "mode": plan["mode"],
        "work_dir": str(work_dir),
        "config_path": str(config_path),
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Prepare a bounded MainNet replay workspace from a validated checkpoint."
    )
    parser.add_argument("--checkpoint", required=True, type=Path)
    parser.add_argument("--work-root", default=Path(DEFAULT_WORK_ROOT), type=Path)
    parser.add_argument("--label", required=True)
    parser.add_argument("--start-height", default=None, type=int)
    parser.add_argument("--target-height", required=True, type=int)
    parser.add_argument("--address", action="append", default=[])
    parser.add_argument("--node-bin", default=Path(DEFAULT_NODE_BIN), type=Path)
    parser.add_argument("--probe-bin", default=Path(DEFAULT_PROBE_BIN), type=Path)
    parser.add_argument("--reference-rpc", default=DEFAULT_REFERENCE_RPC)
    parser.add_argument("--rpc-port", default=DEFAULT_RPC_PORT, type=int)
    parser.add_argument("--p2p-port", default=DEFAULT_P2P_PORT, type=int)
    parser.add_argument("--metrics-port", default=DEFAULT_METRICS_PORT, type=int)
    parser.add_argument("--prepare", action="store_true")
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    plan = build_replay_plan(
        checkpoint=args.checkpoint,
        work_root=args.work_root,
        label=args.label,
        start_height=args.start_height,
        target_height=args.target_height,
        addresses=args.address,
        node_bin=args.node_bin,
        probe_bin=args.probe_bin,
        reference_rpc=args.reference_rpc,
        rpc_port=args.rpc_port,
        p2p_port=args.p2p_port,
        metrics_port=args.metrics_port,
    )
    if args.prepare:
        plan["prepare_result"] = prepare_workspace(plan, force=args.force)
    print(json.dumps(plan, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
