#!/usr/bin/env python3
"""Verify Rust P2P message-command parity against the C# v3.10.1 reference.

Fourth of the surface-parity checks (see verify-native-parity.py,
verify-syscall-parity.py, verify-opcode-parity.py). Covers the P2P wire protocol:
every MessageCommand in the C# reference must exist in the Rust node under the same
name with the same single-byte discriminator.

The discriminator matters more than the name here. These values are written straight
onto the wire; a name can match while its byte does not, and the resulting stream
would be rejected by (or worse, misinterpreted by) every other node on the network.

Where each side lives
---------------------
* C#: `src/Neo/Network/P2P/MessageCommand.cs` in `neo-project/neo` @ v3.10.1.
  Members are 8-space indented and may carry `[ReflectionCache(...)]` attributes.

* Rust: the commands are not a hand-written enum. `MessageCommand` is generated by
  the `p2p_message_command!` macro, whose variant table lives in
  `neo-primitives/src/macros.rs` under `macro_rules! __p2p_message_command_table`.
  Entries look like `Version = 0x00 => "version",`.

  `MessageCommand::Unknown(u8)` is deliberately excluded: it is added by the
  `protocol_enum_with_unknown!` wrapper rather than appearing in the table, and it
  is an implementation detail for preserving unrecognised bytes, not a protocol
  command.

Usage
-----
    python scripts/verify-p2p-parity.py
    python scripts/verify-p2p-parity.py --json reports/p2p-parity.json

Exit codes: 0 = full parity, 1 = differences found, 2 = tooling/IO error.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CACHE_DIR = REPO_ROOT / ".cache" / "csharp-parity"

CSHARP_BASE = "https://raw.githubusercontent.com/neo-project/neo"
CSHARP_REF = os.environ.get("NEO_CSHARP_REF", "v3.10.1")
CSHARP_PATH = "src/Neo/Network/P2P/MessageCommand.cs"

RUST_MACRO_FILE = REPO_ROOT / "neo-primitives" / "src" / "macros.rs"
RUST_TABLE_MACRO = "macro_rules! __p2p_message_command_table"

# C# enum members are 8-space indented; trailing comma optional (last member has none).
CSHARP_COMMAND_RE = re.compile(r"^\s{8}([A-Z][A-Za-z0-9]*)\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*,?\s*$", re.M)
# Rust table entries: `Name = 0xNN => "wire-name",`
RUST_COMMAND_RE = re.compile(r'^\s*([A-Z][A-Za-z0-9]*)\s*=\s*(0x[0-9A-Fa-f]+)\s*=>', re.M)


def fetch_text(url: str) -> str:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    cache_file = CACHE_DIR / (url.replace("://", "_").replace("/", "_"))
    if cache_file.exists():
        return cache_file.read_text(encoding="utf-8")
    try:
        with urllib.request.urlopen(url, timeout=60) as resp:
            text = resp.read().decode("utf-8")
    except urllib.error.HTTPError as exc:
        raise RuntimeError(f"failed to fetch {url}: HTTP {exc.code}") from exc
    cache_file.write_text(text, encoding="utf-8")
    return text


def rust_command_table(src: str) -> str:
    """Return just the __p2p_message_command_table macro body.

    Scoped to the next `macro_rules!` so entries from unrelated macros cannot leak in.
    """
    start = src.find(RUST_TABLE_MACRO)
    if start == -1:
        raise RuntimeError(f"{RUST_TABLE_MACRO} not found in {RUST_MACRO_FILE}")
    nxt = src.find("macro_rules!", start + len(RUST_TABLE_MACRO))
    return src[start:] if nxt == -1 else src[start:nxt]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", help="write the machine-readable report here")
    parser.add_argument("--csharp-ref", default=CSHARP_REF, help="C# git ref to compare against")
    args = parser.parse_args()

    csharp = {
        name: int(value, 0)
        for name, value in CSHARP_COMMAND_RE.findall(fetch_text(f"{CSHARP_BASE}/{args.csharp_ref}/{CSHARP_PATH}"))
    }
    rust = {
        name: int(value, 0)
        for name, value in RUST_COMMAND_RE.findall(rust_command_table(RUST_MACRO_FILE.read_text(encoding="utf-8")))
    }

    missing = sorted(set(csharp) - set(rust))
    extra = sorted(set(rust) - set(csharp))
    mismatched = sorted(
        (name, f"0x{rust[name]:02x}", f"0x{csharp[name]:02x}")
        for name in set(csharp) & set(rust)
        if csharp[name] != rust[name]
    )

    print(f"P2P message command parity (C# {args.csharp_ref} vs Rust)")
    print("=" * 60)
    print(f"C# commands  : {len(csharp)}")
    print(f"Rust commands: {len(rust)}")
    print(f"matched      : {len(set(csharp) & set(rust))}")
    for name in missing:
        print(f"  MISSING in Rust : {name}")
    for name in extra:
        print(f"  EXTRA in Rust   : {name}")
    for name, rust_val, cs_val in mismatched:
        print(f"  VALUE MISMATCH  : {name} rust={rust_val} csharp={cs_val}")
    print("-" * 60)

    ok = not missing and not extra and not mismatched
    print(f"-> {'PARITY' if ok else 'DIFFERENCES'}")

    if args.json:
        out = Path(args.json)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(
            json.dumps(
                {
                    "csharp_commands": len(csharp),
                    "rust_commands": len(rust),
                    "matched": len(set(csharp) & set(rust)),
                    "missing_in_rust": missing,
                    "extra_in_rust": extra,
                    "value_mismatches": [
                        {"command": n, "rust": r, "csharp": c} for n, r, c in mismatched
                    ],
                    "parity": ok,
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        print(f"JSON report: {args.json}")

    return 0 if ok else 1


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (FileNotFoundError, RuntimeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(2)
