[package]
name = "neo-core"
version = "0.3.0"
edition = "2021"
description = "Core functionality for Neo blockchain"
authors = ["R3E Network <jimmy@r3e.network>"]
repository = "https://github.com/r3e-network/neo-rs"
license = "MIT"

[features]
default = []
neo-io = []
neo-cryptography = []

[dependencies]
# External dependencies
num-bigint = "0.4"
num-traits = "0.2"
num-integer = "0.1"
thiserror = "1.0"
derive_more = "0.99"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
byteorder = "1.4"
bytes = "1.4"
log = "0.4"
tokio = { version = "1.28", features = ["full"] }
async-trait = "0.1"
rand = "0.8"
sha2 = "0.10"
ripemd = "0.1"
bs58 = "0.5"
once_cell = "1.19"
tracing = "0.1"

# Internal dependencies
neo-config = { path = "../config" }
neo-io = { path = "../io" }
neo-cryptography = { path = "../cryptography" }
# Temporarily commented out to break dependency cycle
# neo-vm = { path = "../vm" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3.5"

[[bench]]
name = "core_benchmarks"
harness = false
