# Copyright @ 2023 - 2024, R3E Network
# All Rights Reserved

[package]
name = "neo-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
neo-core = { path = "../neo-core" }
neo-vm   = { path = "../neo-vm" }


[features]
default = []

std     = ["neo-core/std"]