[package]
name = "neo-persistence"
version = "0.3.0"
edition = "2021"

[dependencies]
log = "0.4"# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
derive_more = "0.99"
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
futures = "0.3"

# Storage engines
rocksdb = { version = "0.21", optional = true, features = ["snappy", "lz4"] }
sled = { version = "0.34", optional = true }

# Serialization and encoding
bincode = "1.3"
hex = "0.4"
base64 = "0.21"

# Compression
lz4_flex = { version = "0.11", optional = true }
# zstd = { version = "0.13", optional = true } # Temporarily disabled due to C header issues

# Hashing and indexing
blake3 = "1.5"
xxhash-rust = { version = "0.8", features = ["xxh3"] }

# Collections and utilities
indexmap = "2.0"
dashmap = "5.5"
parking_lot = "0.12"
crossbeam = "0.8"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Memory management
bytes = "1.5"

# Metrics and monitoring
metrics = "0.21"

# Tracing and logging
tracing = "0.1"
tracing-subscriber = "0.3"

# Neo dependencies
neo-core = { path = "../core" }
neo-cryptography = { path = "../cryptography" }
neo-io = { path = "../io" }
neo-config = { path = "../config" }

# Cryptography
sha2 = "0.10"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
criterion = "0.5"

[features]
default = ["rocksdb", "compression"]
rocksdb = ["dep:rocksdb"]
sled = ["dep:sled"]
compression = ["dep:lz4_flex"] # removed zstd due to build issues
