[package]
name = "neo-network"
version = "0.3.0"
edition = "2021"

[features]
default = ["compression"]
compression = ["lz4"]


[dependencies]
# Core dependencies
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
derive_more = "0.99"
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }

# Networking
tokio-tungstenite = "0.20"
hyper = { version = "0.14", features = ["full"] }
tower = "0.4"
tower-http = { version = "0.4", features = ["cors", "trace"] }
axum = { version = "0.6", features = ["ws"] }

# Serialization and encoding
bincode = "1.3"
hex = "0.4"
base64 = "0.21"

# Compression
lz4 = { version = "1.24", optional = true }

# Cryptography
rand = "0.8"
sha2 = "0.10"
blake3 = "1.5"
ripemd = "0.1"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Collections and utilities
indexmap = "2.0"
dashmap = "5.5"
uuid = { version = "1.0", features = ["v4"] }

# Tracing and logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Neo dependencies
neo-core = { workspace = true }
neo-cryptography = { path = "../cryptography" }
neo-io = { path = "../io" }
neo-ledger = { workspace = true }

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
wiremock = "0.5"
